local hl = vim.api.nvim_set_hl
local theme = {}

theme.set_highlights = function(opts)
    local c = require('lytmode.colors').get_colors()

    hl(0, 'Normal', { fg = c.lytFront, bg = c.lytBack })
    hl(0, 'ColorColumn', { fg = 'NONE', bg = c.lytCursorDarkDark })
    hl(0, 'Cursor', { fg = c.lytCursorDark, bg = c.lytCursorLight })
    hl(0, 'CursorLine', { bg = c.lytCursorDarkDark })
    hl(0, 'CursorColumn', { fg = 'NONE', bg = c.lytCursorDarkDark })
    hl(0, 'Directory', { fg = c.lytBlue, bg = c.lytBack })
    hl(0, 'DiffAdd', { fg = 'NONE', bg = c.lytDiffGreenLight })
    hl(0, 'DiffChange', { fg = 'NONE', bg = c.lytDiffRedDark })
    hl(0, 'DiffDelete', { fg = 'NONE', bg = c.lytDiffRedLight })
    hl(0, 'DiffText', { fg = 'NONE', bg = c.lytDiffRedLight })
    hl(0, 'EndOfBuffer', { fg = c.lytBack, bg = 'NONE' })
    hl(0, 'ErrorMsg', { fg = c.lytRed, bg = c.lytBack })
    hl(0, 'VertSplit', { fg = c.lytSplitDark, bg = c.lytBack })
    hl(0, 'WinSeparator', { link = 'VertSplit' })
    hl(0, 'Folded', { fg = 'NONE', bg = c.lytFoldBackground })
    hl(0, 'FoldColumn', { fg = c.lytLineNumber, bg = c.lytBack })
    hl(0, 'SignColumn', { fg = 'NONE', bg = c.lytBack })
    hl(0, 'IncSearch', { fg = c.lytNone, bg = c.lytSearchCurrent })
    hl(0, 'LineNr', { fg = c.lytLineNumber, bg = c.lytBack })
    hl(0, 'CursorLineNr', { fg = c.lytPopupFront, bg = c.lytBack })
    hl(0, 'MatchParen', { fg = c.lytNone, bg = c.lytDimHighlight })
    hl(0, 'ModeMsg', { fg = c.lytFront, bg = c.lytLeftDark })
    hl(0, 'MoreMsg', { fg = c.lytFront, bg = c.lytLeftDark })
    hl(0, 'NonText', { fg = c.lytLineNumber, bg = c.lytNone })
    hl(0, 'Pmenu', { fg = c.lytPopupFront, bg = c.lytPopupBack })
    hl(0, 'PmenuSel', { fg = c.lytPopupFront, bg = c.lytPopupHighlightBlue})
    hl(0, 'PmenuSbar', { fg = 'NONE', bg = c.lytPopupHighlightGray })
    hl(0, 'PmenuThumb', { fg = 'NONE', bg = c.lytPopupFront })
    hl(0, 'Question', { fg = c.lytBlue, bg = c.lytBack })
    hl(0, 'Search', { fg = c.lytNone, bg = c.lytSearch })
    hl(0, 'SpecialKey', { fg = c.lytBlue, bg = c.lytNone })
    hl(0, 'StatusLine', { fg = c.lytFront, bg = c.lytLeftMid })
    hl(0, 'StatusLineNC', { fg = c.lytFront, bg = opts.transparent and c.lytBack or c.lytLeftDark })
    hl(0, 'TabLine', { fg = c.lytFront, bg = c.lytTabOther })
    hl(0, 'TabLineFill', { fg = c.lytFront, bg = c.lytTabOutside })
    hl(0, 'TabLineSel', { fg = c.lytFront, bg = c.lytTabCurrent })
    hl(0, 'Title', { fg = c.lytNone, bg = c.lytNone, bold = true })
    hl(0, 'Visual', { fg = c.lytNone, bg = c.lytSelection })
    hl(0, 'VisualNOS', { fg = c.lytNone, bg = c.lytSelection })
    hl(0, 'WarningMsg', { fg = c.lytRed, bg = c.lytBack, bold = true })
    hl(0, 'WildMenu', { fg = c.lytNone, bg = c.lytSelection })
    hl(0, 'Comment', { fg = c.lytGray, bg = 'NONE', italic = opts.italic_comments })
    hl(0, 'Constant', { fg = c.lytBlue, bg = 'NONE' })
    hl(0, 'String', { fg = c.lytLightViolet, bg = 'NONE' })
    hl(0, 'Character', { fg = c.lytLightViolet, bg = 'NONE' })
    hl(0, 'Number', { fg = c.lytLightViolet, bg = 'NONE' })
    hl(0, 'Boolean', { fg = c.lytLightViolet, bg = 'NONE' })
    hl(0, 'Float', { fg = c.lytLightViolet, bg = 'NONE' })
    hl(0, 'Identifier', { fg = c.lytLightBlue, bg = 'NONE' })
    hl(0, 'Function', { fg = c.lytYellow, bg = 'NONE' })
    hl(0, 'Statement', { fg = c.lytPink, bg = 'NONE' })
    hl(0, 'Conditional', { fg = c.lytPink, bg = 'NONE' })
    hl(0, 'Repeat', { fg = c.lytPink, bg = 'NONE' })
    hl(0, 'Label', { fg = c.lytPink, bg = 'NONE' })
    hl(0, 'Operator', { fg = c.lytFront, bg = 'NONE' })
    hl(0, 'Keyword', { fg = c.lytPink, bg = 'NONE' })
    hl(0, 'Exception', { fg = c.lytPink, bg = 'NONE' })
    hl(0, 'PreProc', { fg = c.lytPink, bg = 'NONE' })
    hl(0, 'Include', { fg = c.lytPink, bg = 'NONE' })
    hl(0, 'Define', { fg = c.lytPink, bg = 'NONE' })
    hl(0, 'Macro', { fg = c.lytPink, bg = 'NONE' })
    hl(0, 'Type', { fg = c.lytBlue, bg = 'NONE' })
    hl(0, 'StorageClass', { fg = c.lytBlue, bg = 'NONE' })
    hl(0, 'Structure', { fg = c.lytGreen, bg = 'NONE' })
    hl(0, 'Typedef', { fg = c.lytBlue, bg = 'NONE' })
    hl(0, 'Special', { fg = c.lytYellowOrange, bg = 'NONE' })
    hl(0, 'SpecialChar', { fg = c.lytFront, bg = 'NONE' })
    hl(0, 'Tag', { fg = c.lytFront, bg = 'NONE' })
    hl(0, 'Delimiter', { fg = c.lytFront, bg = 'NONE' })
    hl(0, 'SpecialComment', { fg = c.lytGray, bg = 'NONE' })
    hl(0, 'Debug', { fg = c.lytFront, bg = 'NONE' })
    hl(0, 'Underlined', { fg = c.lytNone, bg = 'NONE', underline = true })
    hl(0, 'Conceal', { fg = c.lytFront, bg = c.lytBack })
    hl(0, 'Ignore', { fg = c.lytFront, bg = 'NONE' })
    hl(0, 'Error', { fg = c.lytRed, bg = c.lytBack, undercurl = true, sp = c.lytRed })
    hl(0, 'Todo', { fg = c.lytLightViolet, bg = c.lytBack, bold = true })
    hl(0, 'SpellBad', { fg = 'NONE', undercurl = true, sp = c.lytRed })
    hl(0, 'SpellCap', { fg = 'NONE', undercurl = true, sp = c.lytYellow })
    hl(0, 'SpellRare', { fg = 'NONE', undercurl = true, sp = c.lytViolet })
    hl(0, 'SpellLocal', { fg = 'NONE', undercurl = true, sp = c.lytBlue })
    hl(0, 'Whitespace', { fg = c.lytLineNumber })
    hl(0, 'NormalFloat', { bg = c.lytPopupBack })
    hl(0, 'WinBar', { fg = c.lytFront, bg = c.lytBack, bold = true })
    hl(0, 'WinBarNc', { fg = c.lytFront, bg = c.lytBack })
    hl(0, 'QuickFixLine', { bold = true })

    -- Treesitter
    hl(0, '@error', { fg = c.lytRed, bg = 'NONE' }) -- Legacy
    hl(0, '@punctuation.bracket', { fg = c.lytPink, bg = 'NONE' })
    hl(0, '@punctuation.special', { fg = c.lytFront, bg = 'NONE' })
    hl(0, '@punctuation.delimiter', { fg = c.lytFront, bg = 'NONE' })
    hl(0, '@comment', { fg = c.lytGray, bg = 'NONE', italic = opts.italic_comments })
    hl(0, '@comment.note', { fg = c.lytGreen, bg = 'NONE', bold = true })
    hl(0, '@comment.warning', { fg = c.lytYellowOrange, bg = 'NONE', bold = true })
    hl(0, '@comment.error', { fg = c.lytRed, bg = 'NONE', bold = true })
    hl(0, '@constant', { fg = c.lytAccentBlue, bg = 'NONE' })
    hl(0, '@constant.builtin', { fg = c.lytLightViolet, bg = 'NONE' })
    hl(0, '@constant.macro', { fg = c.lytGreen, bg = 'NONE' })
    hl(0, '@string.regexp', { fg = c.lytLightViolet, bg = 'NONE' })
    hl(0, '@string', { fg = c.lytLightViolet, bg = 'NONE' })
    hl(0, '@character', { fg = c.lytLightViolet, bg = 'NONE' })
    hl(0, '@number', { fg = c.lytLightViolet, bg = 'NONE' })
    hl(0, '@number.float', { fg = c.lytLightViolet, bg = 'NONE' })
    hl(0, '@boolean', { fg = c.lytLightViolet, bg = 'NONE' })
    hl(0, '@annotation', { fg = c.lytYellow, bg = 'NONE' })
    hl(0, '@attribute', { fg = c.lytYellow, bg = 'NONE' })
    hl(0, '@attribute.builtin', { fg = c.lytGreen, bg = 'NONE' })
    hl(0, '@module', { fg = c.lytGreen, bg = 'NONE' })
    hl(0, '@function', { fg = c.lytYellow, bg = 'NONE' })
    hl(0, '@function.builtin', { fg = c.lytYellow, bg = 'NONE' })
    hl(0, '@function.macro', { fg = c.lytYellow, bg = 'NONE' })
    hl(0, '@function.method', { fg = c.lytYellow, bg = 'NONE' })
    hl(0, '@define', { fg = c.lytPink, bg = 'NONE' })
    hl(0, '@variable', { fg = c.lytLightBlue, bg = 'NONE' })
    hl(0, '@variable.builtin', { fg = c.lytBlue, bg = 'NONE' })
    hl(0, '@variable.parameter', { fg = c.lytLightBlue, bg = 'NONE' })
    hl(0, '@variable.parameter.reference', { fg = c.lytLightBlue, bg = 'NONE' })
    hl(0, '@variable.member', { fg = c.lytLightBlue, bg = 'NONE' })
    hl(0, '@property', { fg = c.lytLightBlue, bg = 'NONE' })
    hl(0, '@constructor', { fg = c.lytBlue, bg = 'NONE' })
    hl(0, '@label', { fg = c.lytLightBlue, bg = 'NONE' })
    hl(0, '@keyword', { fg = c.lytPink, bg = 'NONE' })
    hl(0, '@keyword.conditional', { fg = c.lytPink, bg = 'NONE' })
    hl(0, '@keyword.repeat', { fg = c.lytPink, bg = 'NONE' })
    hl(0, '@keyword.return', { fg = c.lytPink, bg = 'NONE' })
    hl(0, '@keyword.exception', { fg = c.lytPink, bg = 'NONE' })
    hl(0, '@keyword.import', { fg = c.lytPink, bg = 'NONE' })
    hl(0, '@operator', { fg = c.lytFront, bg = 'NONE' })
    hl(0, '@type', { fg = c.lytGreen, bg = 'NONE' })
    hl(0, '@type.qualifier', { fg = c.lytBlue, bg = 'NONE' })
    hl(0, '@structure', { fg = c.lytLightBlue, bg = 'NONE' })
    hl(0, '@tag', { fg = c.lytBlue, bg = 'NONE' })
    hl(0, '@tag.builtin', { fg = c.lytBlue, bg = 'NONE' })
    hl(0, '@tag.delimiter', { fg = c.lytGray, bg = 'NONE' })
    hl(0, '@tag.attribute', { fg = c.lytLightBlue, bg = 'NONE' })

    hl(0, '@text', { fg = c.lytFront, bg = 'NONE' }) -- Legacy
    hl(0, '@markup.strong', { fg = c.lytYellow, bold = true })
    hl(0, '@markup.italic', { fg = c.lytLightViolet, bg = 'NONE', italic = true })
    hl(0, '@markup.underline', { fg = c.lytYellowOrange, bg = 'NONE', underline = true })
    hl(0, '@markup.strikethrough', { fg = c.lytFront, bg = 'NONE', strikethrough = true })
    hl(0, '@markup.heading.1', { fg = c.lytYellow, bold = true })
    hl(0, '@markup.heading.2', { fg = c.lytViolet, bold = true })
    hl(0, '@markup.heading.3', { fg = c.lytAccentBlue, bold = true })
    hl(0, '@markup.heading.4', { fg = c.lytGreen, bold = true })
    hl(0, '@markup.heading.5', { fg = c.lytPopupFront, bold = true })
    hl(0, '@markup.heading.6', { fg = c.lytGray, bold = true })
    hl(0, '@markup.raw', { fg = c.lytFront, bg = 'NONE' })
    hl(0, '@markup.raw.markdown', { fg = c.lytOrange, bg = 'NONE' })
    hl(0, '@markup.raw.markdown_inline', { fg = c.lytFront, bg = c.lytBackDark })
    hl(0, '@markup.link.label', { fg = c.lytPink, bg = 'NONE', underline = opts.underline_links })
    hl(0, '@markup.link.url', { fg = c.lytFront, bg = 'NONE', underline = opts.underline_links })
    hl(0, '@markup.list', { link = 'Todo' })
    hl(0, '@textReference', { fg = c.lytOrange })
    hl(0, '@stringEscape', { fg = c.lytLightViolet, bold = true })

    hl(0, '@diff.plus', { link = 'DiffAdd' })
    hl(0, '@diff.minus', { link = 'DiffDelete' })
    hl(0, '@diff.delta', { link = 'DiffChange' })

    -- LSP semantic tokens
    hl(0, '@type.builtin', { fg = c.lytBlue, bg = 'NONE' })
    hl(0, '@lsp.typemod.type.defaultLibrary', { link = '@type.builtin' })
    hl(0, '@lsp.type.type', { link = '@type' })
    hl(0, '@lsp.type.typeParameter', { link = '@type' })
    hl(0, '@lsp.type.macro', { link = '@constant' })
    hl(0, '@lsp.type.enumMember', { link = '@constant' })
    hl(0, '@lsp.typemod.variable.readonly', { link = '@constant' })
    hl(0, '@lsp.typemod.property.readonly', { link = '@constant' })
    hl(0, '@lsp.typemod.variable.constant', { link = '@constant' })
    hl(0, '@lsp.type.member', { link = '@function' })
    hl(0, '@lsp.type.keyword', { link = '@keyword' })
    hl(0, '@lsp.typemod.keyword.controlFlow', { fg = c.lytPink, bg = 'NONE' })
    hl(0, '@lsp.type.comment.c', { fg = c.lytDimHighlight, bg = 'NONE' })
    hl(0, '@lsp.type.comment.cpp', { fg = c.lytDimHighlight, bg = 'NONE' })
    hl(0, '@event', { link = 'Identifier' })
    hl(0, '@interface', { link = 'Identifier' })
    hl(0, '@modifier', { link = 'Identifier' })
    hl(0, '@regexp', { fg = c.lytRed, bg = 'NONE' })
    hl(0, '@decorator', { link = 'Identifier' })

    -- Markdown
    hl(0, 'markdownBold', { fg = c.lytYellow, bold = true })
    hl(0, 'markdownCode', { fg = c.lytOrange, bg = 'NONE' })
    hl(0, 'markdownRule', { fg = c.lytBlue, bold = true })
    hl(0, 'markdownCodeDelimiter', { fg = c.lytFront, bg = 'NONE' })
    hl(0, 'markdownHeadingDelimiter', { fg = c.lytBlue, bg = 'NONE' })
    hl(0, 'markdownFootnote', { fg = c.lytOrange, bg = 'NONE' })
    hl(0, 'markdownFootnoteDefinition', { fg = c.lytOrange })
    hl(0, 'markdownUrl', { fg = c.lytFront, bg = 'NONE', underline = true })
    hl(0, 'markdownLinkText', { fg = c.lytPink })
    hl(0, 'markdownEscape', { fg = c.lytOrange })

    -- Asciidoc
    hl(0, 'asciidocAttributeEntry', { fg = c.lytYellowOrange })
    hl(0, 'asciidocAttributeList', { fg = c.lytPink })
    hl(0, 'asciidocAttributeRef', { fg = c.lytYellowOrange })
    hl(0, 'asciidocHLabel', { fg = c.lytBlue, bold = true })
    hl(0, 'asciidocListingBlock', { fg = c.lytOrange })
    hl(0, 'asciidocMacroAttributes', { fg = c.lytYellowOrange })
    hl(0, 'asciidocOneLineTitle', { fg = c.lytBlue, bold = true })
    hl(0, 'asciidocPassthroughBlock', { fg = c.lytBlue })
    hl(0, 'asciidocQuotedMonospaced', { fg = c.lytOrange })
    hl(0, 'asciidocTriplePlusPassthrough', { fg = c.lytYellow })
    hl(0, 'asciidocMacro', { fg = c.lytPink })
    hl(0, 'asciidocAdmonition', { fg = c.lytOrange })
    hl(0, 'asciidocQuotedEmphasized', { fg = c.lytBlue, italic = true })
    hl(0, 'asciidocQuotedEmphasized2', { fg = c.lytBlue, italic = true })
    hl(0, 'asciidocQuotedEmphasizedItalic', { fg = c.lytBlue, italic = true })
    hl(0, 'asciidocBackslash', { link = 'Keyword' })
    hl(0, 'asciidocQuotedBold', { link = 'markdownBold' })
    hl(0, 'asciidocQuotedMonospaced2', { link = 'asciidocQuotedMonospaced' })
    hl(0, 'asciidocQuotedUnconstrainedBold', { link = 'asciidocQuotedBold' })
    hl(0, 'asciidocQuotedUnconstrainedEmphasized', { link = 'asciidocQuotedEmphasized' })
    hl(0, 'asciidocURL', { link = 'markdownUrl' })

    -- JSON
    hl(0, 'jsonKeyword', { fg = c.lytLightBlue, bg = 'NONE' })
    hl(0, 'jsonEscape', { fg = c.lytYellowOrange, bg = 'NONE' })
    hl(0, 'jsonNull', { fg = c.lytBlue, bg = 'NONE' })
    hl(0, 'jsonBoolean', { fg = c.lytLightViolet, bg = 'NONE' })

    -- HTML
    hl(0, 'htmlTag', { fg = c.lytGray, bg = 'NONE' })
    hl(0, 'htmlEndTag', { fg = c.lytGray, bg = 'NONE' })
    hl(0, 'htmlTagName', { fg = c.lytBlue, bg = 'NONE' })
    hl(0, 'htmlSpecialTagName', { fg = c.lytBlue, bg = 'NONE' })
    hl(0, 'htmlArg', { fg = c.lytLightBlue, bg = 'NONE' })

    -- PHP
    hl(0, 'phpStaticClasses', { fg = c.lytGreen, bg = 'NONE' })
    hl(0, 'phpMethod', { fg = c.lytYellow, bg = 'NONE' })
    hl(0, 'phpClass', { fg = c.lytGreen, bg = 'NONE' })
    hl(0, 'phpFunction', { fg = c.lytYellow, bg = 'NONE' })
    hl(0, 'phpInclude', { fg = c.lytBlue, bg = 'NONE' })
    hl(0, 'phpUseClass', { fg = c.lytGreen, bg = 'NONE' })
    hl(0, 'phpRegion', { fg = c.lytGreen, bg = 'NONE' })
    hl(0, 'phpMethodsVar', { fg = c.lytLightBlue, bg = 'NONE' })

    -- CSS
    hl(0, 'cssBraces', { fg = c.lytFront, bg = 'NONE' })
    hl(0, 'cssInclude', { fg = c.lytPink, bg = 'NONE' })
    hl(0, 'cssTagName', { fg = c.lytYellowOrange, bg = 'NONE' })
    hl(0, 'cssClassName', { fg = c.lytYellowOrange, bg = 'NONE' })
    hl(0, 'cssPseudoClass', { fg = c.lytYellowOrange, bg = 'NONE' })
    hl(0, 'cssPseudoClassId', { fg = c.lytYellowOrange, bg = 'NONE' })
    hl(0, 'cssPseudoClassLang', { fg = c.lytYellowOrange, bg = 'NONE' })
    hl(0, 'cssIdentifier', { fg = c.lytYellowOrange, bg = 'NONE' })
    hl(0, 'cssProp', { fg = c.lytLightBlue, bg = 'NONE' })
    hl(0, 'cssDefinition', { fg = c.lytLightBlue, bg = 'NONE' })
    hl(0, 'cssAttr', { fg = c.lytOrange, bg = 'NONE' })
    hl(0, 'cssAttrRegion', { fg = c.lytOrange, bg = 'NONE' })
    hl(0, 'cssColor', { fg = c.lytOrange, bg = 'NONE' })
    hl(0, 'cssFunction', { fg = c.lytOrange, bg = 'NONE' })
    hl(0, 'cssFunctionName', { fg = c.lytOrange, bg = 'NONE' })
    hl(0, 'cssVendor', { fg = c.lytOrange, bg = 'NONE' })
    hl(0, 'cssValueNumber', { fg = c.lytOrange, bg = 'NONE' })
    hl(0, 'cssValueLength', { fg = c.lytOrange, bg = 'NONE' })
    hl(0, 'cssUnitDecorators', { fg = c.lytOrange, bg = 'NONE' })
    hl(0, 'cssStyle', { fg = c.lytLightBlue, bg = 'NONE' })
    hl(0, 'cssImportant', { fg = c.lytBlue, bg = 'NONE' })

    -- JavaScript
    hl(0, 'jsVariableDef', { fg = c.lytLightBlue, bg = 'NONE' })
    hl(0, 'jsFuncArgs', { fg = c.lytLightBlue, bg = 'NONE' })
    hl(0, 'jsFuncBlock', { fg = c.lytLightBlue, bg = 'NONE' })
    hl(0, 'jsRegexpString', { fg = c.lytLightRed, bg = 'NONE' })
    hl(0, 'jsThis', { fg = c.lytBlue, bg = 'NONE' })
    hl(0, 'jsOperatorKeyword', { fg = c.lytPink, bg = 'NONE' })
    hl(0, 'jsDestructuringBlock', { fg = c.lytLightBlue, bg = 'NONE' })
    hl(0, 'jsObjectKey', { fg = c.lytLightBlue, bg = 'NONE' })
    hl(0, 'jsGlobalObjects', { fg = c.lytGreen, bg = 'NONE' })
    hl(0, 'jsModuleKeyword', { fg = c.lytLightBlue, bg = 'NONE' })
    hl(0, 'jsClassDefinition', { fg = c.lytGreen, bg = 'NONE' })
    hl(0, 'jsClassKeyword', { fg = c.lytPink, bg = 'NONE' })
    hl(0, 'jsExtendsKeyword', { fg = c.lytPink, bg = 'NONE' })
    hl(0, 'jsExportDefault', { fg = c.lytPink, bg = 'NONE' })
    hl(0, 'jsFuncCall', { fg = c.lytYellow, bg = 'NONE' })
    hl(0, 'jsObjectValue', { fg = c.lytLightBlue, bg = 'NONE' })
    hl(0, 'jsParen', { fg = c.lytLightBlue, bg = 'NONE' })
    hl(0, 'jsObjectProp', { fg = c.lytLightBlue, bg = 'NONE' })
    hl(0, 'jsIfElseBlock', { fg = c.lytLightBlue, bg = 'NONE' })
    hl(0, 'jsParenIfElse', { fg = c.lytLightBlue, bg = 'NONE' })
    hl(0, 'jsSpreadOperator', { fg = c.lytLightBlue, bg = 'NONE' })
    hl(0, 'jsSpreadExpression', { fg = c.lytLightBlue, bg = 'NONE' })

    -- Typescript
    hl(0, '@type.builtin.typescript', { link = '@type' })
    hl(0, '@type.builtin.tsx', { link = '@type' })
    hl(0, 'typescriptLabel', { fg = c.lytLightBlue, bg = 'NONE' })
    hl(0, 'typescriptExceptions', { fg = c.lytLightBlue, bg = 'NONE' })
    hl(0, 'typescriptBraces', { fg = c.lytFront, bg = 'NONE' })
    hl(0, 'typescriptEndColons', { fg = c.lytLightBlue, bg = 'NONE' })
    hl(0, 'typescriptParens', { fg = c.lytFront, bg = 'NONE' })
    hl(0, 'typescriptDocTags', { fg = c.lytBlue, bg = 'NONE' })
    hl(0, 'typescriptDocComment', { fg = c.lytGreen, bg = 'NONE' })
    hl(0, 'typescriptLogicSymbols', { fg = c.lytLightBlue, bg = 'NONE' })
    hl(0, 'typescriptImport', { fg = c.lytPink, bg = 'NONE' })
    hl(0, 'typescriptBOM', { fg = c.lytLightBlue, bg = 'NONE' })
    hl(0, 'typescriptVariableDeclaration', { fg = c.lytLightBlue, bg = 'NONE' })
    hl(0, 'typescriptVariable', { fg = c.lytBlue, bg = 'NONE' })
    hl(0, 'typescriptExport', { fg = c.lytPink, bg = 'NONE' })
    hl(0, 'typescriptAliasDeclaration', { fg = c.lytGreen, bg = 'NONE' })
    hl(0, 'typescriptAliasKeyword', { fg = c.lytPink, bg = 'NONE' })
    hl(0, 'typescriptClassName', { fg = c.lytGreen, bg = 'NONE' })
    hl(0, 'typescriptAccessibilityModifier', { fg = c.lytBlue, bg = 'NONE' })
    hl(0, 'typescriptOperator', { fg = c.lytBlue, bg = 'NONE' })
    hl(0, 'typescriptArrowFunc', { fg = c.lytBlue, bg = 'NONE' })
    hl(0, 'typescriptMethodAccessor', { fg = c.lytBlue, bg = 'NONE' })
    hl(0, 'typescriptMember', { fg = c.lytYellow, bg = 'NONE' })
    hl(0, 'typescriptTypeReference', { fg = c.lytGreen, bg = 'NONE' })
    hl(0, 'typescriptTemplateSB', { fg = c.lytYellowOrange, bg = 'NONE' })
    hl(0, 'typescriptArrowFuncArg', { fg = c.lytLightBlue, bg = 'NONE' })
    hl(0, 'typescriptParamImpl', { fg = c.lytLightBlue, bg = 'NONE' })
    hl(0, 'typescriptFuncComma', { fg = c.lytLightBlue, bg = 'NONE' })
    hl(0, 'typescriptCastKeyword', { fg = c.lytLightBlue, bg = 'NONE' })
    hl(0, 'typescriptCall', { fg = c.lytBlue, bg = 'NONE' })
    hl(0, 'typescriptCase', { fg = c.lytLightBlue, bg = 'NONE' })
    hl(0, 'typescriptReserved', { fg = c.lytPink, bg = 'NONE' })
    hl(0, 'typescriptDefault', { fg = c.lytLightBlue, bg = 'NONE' })
    hl(0, 'typescriptDecorator', { fg = c.lytYellow, bg = 'NONE' })
    hl(0, 'typescriptPredefinedType', { fg = c.lytGreen, bg = 'NONE' })
    hl(0, 'typescriptClassHeritage', { fg = c.lytGreen, bg = 'NONE' })
    hl(0, 'typescriptClassExtends', { fg = c.lytBlue, bg = 'NONE' })
    hl(0, 'typescriptClassKeyword', { fg = c.lytPink, bg = 'NONE' })
    hl(0, 'typescriptBlock', { fg = c.lytLightBlue, bg = 'NONE' })
    hl(0, 'typescriptDOMDocProp', { fg = c.lytLightBlue, bg = 'NONE' })
    hl(0, 'typescriptTemplateSubstitution', { fg = c.lytLightBlue, bg = 'NONE' })
    hl(0, 'typescriptClassBlock', { fg = c.lytLightBlue, bg = 'NONE' })
    hl(0, 'typescriptFuncCallArg', { fg = c.lytLightBlue, bg = 'NONE' })
    hl(0, 'typescriptIndexExpr', { fg = c.lytLightBlue, bg = 'NONE' })
    hl(0, 'typescriptConditionalParen', { fg = c.lytLightBlue, bg = 'NONE' })
    hl(0, 'typescriptArray', { fg = c.lytYellow, bg = 'NONE' })
    hl(0, 'typescriptES6SetProp', { fg = c.lytLightBlue, bg = 'NONE' })
    hl(0, 'typescriptObjectLiteral', { fg = c.lytLightBlue, bg = 'NONE' })
    hl(0, 'typescriptTypeParameter', { fg = c.lytGreen, bg = 'NONE' })
    hl(0, 'typescriptEnumKeyword', { fg = c.lytPink, bg = 'NONE' })
    hl(0, 'typescriptEnum', { fg = c.lytGreen, bg = 'NONE' })
    hl(0, 'typescriptLoopParen', { fg = c.lytLightBlue, bg = 'NONE' })
    hl(0, 'typescriptParenExp', { fg = c.lytLightBlue, bg = 'NONE' })
    hl(0, 'typescriptModule', { fg = c.lytLightBlue, bg = 'NONE' })
    hl(0, 'typescriptAmbientDeclaration', { fg = c.lytBlue, bg = 'NONE' })
    hl(0, 'typescriptFuncTypeArrow', { fg = c.lytBlue, bg = 'NONE' })
    hl(0, 'typescriptInterfaceHeritage', { fg = c.lytGreen, bg = 'NONE' })
    hl(0, 'typescriptInterfaceName', { fg = c.lytGreen, bg = 'NONE' })
    hl(0, 'typescriptInterfaceKeyword', { fg = c.lytPink, bg = 'NONE' })
    hl(0, 'typescriptInterfaceExtends', { fg = c.lytBlue, bg = 'NONE' })
    hl(0, 'typescriptGlobal', { fg = c.lytGreen, bg = 'NONE' })
    hl(0, 'typescriptAsyncFuncKeyword', { fg = c.lytPink, bg = 'NONE' })
    hl(0, 'typescriptFuncKeyword', { fg = c.lytPink, bg = 'NONE' })
    hl(0, 'typescriptGlobalMethod', { fg = c.lytYellow, bg = 'NONE' })
    hl(0, 'typescriptPromiseMethod', { fg = c.lytYellow, bg = 'NONE' })

    -- XML
    hl(0, 'xmlTag', { fg = c.lytBlue, bg = 'NONE' })
    hl(0, 'xmlTagName', { fg = c.lytBlue, bg = 'NONE' })
    hl(0, 'xmlEndTag', { fg = c.lytBlue, bg = 'NONE' })

    -- Ruby
    hl(0, 'rubyClassNameTag', { fg = c.lytGreen, bg = 'NONE' })
    hl(0, 'rubyClassName', { fg = c.lytGreen, bg = 'NONE' })
    hl(0, 'rubyModuleName', { fg = c.lytGreen, bg = 'NONE' })
    hl(0, 'rubyConstant', { fg = c.lytGreen, bg = 'NONE' })

    -- Golang
    hl(0, 'goPackage', { fg = c.lytBlue, bg = 'NONE' })
    hl(0, 'goImport', { fg = c.lytBlue, bg = 'NONE' })
    hl(0, 'goVar', { fg = c.lytBlue, bg = 'NONE' })
    hl(0, 'goConst', { fg = c.lytBlue, bg = 'NONE' })
    hl(0, 'goStatement', { fg = c.lytPink, bg = 'NONE' })
    hl(0, 'goType', { fg = c.lytGreen, bg = 'NONE' })
    hl(0, 'goSignedInts', { fg = c.lytGreen, bg = 'NONE' })
    hl(0, 'goUnsignedInts', { fg = c.lytGreen, bg = 'NONE' })
    hl(0, 'goFloats', { fg = c.lytGreen, bg = 'NONE' })
    hl(0, 'goComplexes', { fg = c.lytGreen, bg = 'NONE' })
    hl(0, 'goBuiltins', { fg = c.lytYellow, bg = 'NONE' })
    hl(0, 'goBoolean', { fg = c.lytLightViolet, bg = 'NONE' })
    hl(0, 'goPredefinedIdentifiers', { fg = c.lytBlue, bg = 'NONE' })
    hl(0, 'goTodo', { fg = c.lytGreen, bg = 'NONE' })
    hl(0, 'goDeclaration', { fg = c.lytBlue, bg = 'NONE' })
    hl(0, 'goDeclType', { fg = c.lytBlue, bg = 'NONE' })
    hl(0, 'goTypeDecl', { fg = c.lytBlue, bg = 'NONE' })
    hl(0, 'goTypeName', { fg = c.lytGreen, bg = 'NONE' })
    hl(0, 'goVarAssign', { fg = c.lytLightBlue, bg = 'NONE' })
    hl(0, 'goVarDefs', { fg = c.lytLightBlue, bg = 'NONE' })
    hl(0, 'goReceiver', { fg = c.lytFront, bg = 'NONE' })
    hl(0, 'goReceiverType', { fg = c.lytFront, bg = 'NONE' })
    hl(0, 'goFunctionCall', { fg = c.lytYellow, bg = 'NONE' })
    hl(0, 'goMethodCall', { fg = c.lytYellow, bg = 'NONE' })
    hl(0, 'goSingleDecl', { fg = c.lytLightBlue, bg = 'NONE' })

    -- Python
    hl(0, 'pythonStatement', { fg = c.lytBlue, bg = 'NONE' })
    hl(0, 'pythonOperator', { fg = c.lytBlue, bg = 'NONE' })
    hl(0, 'pythonException', { fg = c.lytPink, bg = 'NONE' })
    hl(0, 'pythonExClass', { fg = c.lytGreen, bg = 'NONE' })
    hl(0, 'pythonBuiltinObj', { fg = c.lytLightBlue, bg = 'NONE' })
    hl(0, 'pythonBuiltinType', { fg = c.lytGreen, bg = 'NONE' })
    hl(0, 'pythonBoolean', { fg = c.lytLightViolet, bg = 'NONE' })
    hl(0, 'pythonNone', { fg = c.lytBlue, bg = 'NONE' })
    hl(0, 'pythonTodo', { fg = c.lytBlue, bg = 'NONE' })
    hl(0, 'pythonClassVar', { fg = c.lytBlue, bg = 'NONE' })
    hl(0, 'pythonClassDef', { fg = c.lytGreen, bg = 'NONE' })
    hl(0, '@constructor.python', { fg = c.lytGreen, bg = 'NONE' })

    -- TeX
    hl(0, 'texStatement', { fg = c.lytBlue, bg = 'NONE' })
    hl(0, 'texBeginEnd', { fg = c.lytYellow, bg = 'NONE' })
    hl(0, 'texBeginEndName', { fg = c.lytLightBlue, bg = 'NONE' })
    hl(0, 'texOption', { fg = c.lytLightBlue, bg = 'NONE' })
    hl(0, 'texBeginEndModifier', { fg = c.lytLightBlue, bg = 'NONE' })
    hl(0, 'texDocType', { fg = c.lytPink, bg = 'NONE' })
    hl(0, 'texDocTypeArgs', { fg = c.lytLightBlue, bg = 'NONE' })

    -- Git
    hl(0, 'gitcommitHeader', { fg = c.lytGray, bg = 'NONE' })
    hl(0, 'gitcommitOnBranch', { fg = c.lytGray, bg = 'NONE' })
    hl(0, 'gitcommitBranch', { fg = c.lytPink, bg = 'NONE' })
    hl(0, 'gitcommitComment', { fg = c.lytGray, bg = 'NONE' })
    hl(0, 'gitcommitSelectedType', { fg = c.lytGreen, bg = 'NONE' })
    hl(0, 'gitcommitSelectedFile', { fg = c.lytGreen, bg = 'NONE' })
    hl(0, 'gitcommitDiscardedType', { fg = c.lytRed, bg = 'NONE' })
    hl(0, 'gitcommitDiscardedFile', { fg = c.lytRed, bg = 'NONE' })
    hl(0, 'gitcommitOverflow', { fg = c.lytRed, bg = 'NONE' })
    hl(0, 'gitcommitSummary', { fg = c.lytPink, bg = 'NONE' })
    hl(0, 'gitcommitBlank', { fg = c.lytPink, bg = 'NONE' })

    -- Lua
    hl(0, 'luaFuncCall', { fg = c.lytYellow, bg = 'NONE' })
    hl(0, 'luaFuncArgName', { fg = c.lytLightBlue, bg = 'NONE' })
    hl(0, 'luaFuncKeyword', { fg = c.lytPink, bg = 'NONE' })
    hl(0, 'luaLocal', { fg = c.lytPink, bg = 'NONE' })
    hl(0, 'luaBuiltIn', { fg = c.lytBlue, bg = 'NONE' })

    -- SH
    hl(0, 'shDeref', { fg = c.lytLightBlue, bg = 'NONE' })
    hl(0, 'shVariable', { fg = c.lytLightBlue, bg = 'NONE' })

    -- SQL
    hl(0, 'sqlKeyword', { fg = c.lytPink, bg = 'NONE' })
    hl(0, 'sqlFunction', { fg = c.lytYellow, bg = 'NONE' })
    hl(0, 'sqlOperator', { fg = c.lytPink, bg = 'NONE' })

    -- YAML
    hl(0, 'yamlKey', { fg = c.lytBlue, bg = 'NONE' })
    hl(0, 'yamlConstant', { fg = c.lytBlue, bg = 'NONE' })

    -- Gitgutter
    hl(0, 'GitGutterAdd', { fg = c.lytGreen, bg = 'NONE' })
    hl(0, 'GitGutterChange', { fg = c.lytYellow, bg = 'NONE' })
    hl(0, 'GitGutterDelete', { fg = c.lytRed, bg = 'NONE' })

    -- Git Signs
    hl(0, 'GitSignsAdd', { fg = c.lytGreen, bg = 'NONE' })
    hl(0, 'GitSignsChange', { fg = c.lytYellow, bg = 'NONE' })
    hl(0, 'GitSignsDelete', { fg = c.lytRed, bg = 'NONE' })
    hl(0, 'GitSignsAddLn', { fg = c.lytBack, bg = c.lytGreen })
    hl(0, 'GitSignsChangeLn', { fg = c.lytBack, bg = c.lytYellow })
    hl(0, 'GitSignsDeleteLn', { fg = c.lytBack, bg = c.lytRed })

    -- NvimTree
    hl(0, 'NvimTreeRootFolder', { fg = c.lytFront, bg = 'NONE', bold = true })
    hl(0, 'NvimTreeGitDirty', { fg = c.lytYellow, bg = 'NONE' })
    hl(0, 'NvimTreeGitNew', { fg = c.lytGreen, bg = 'NONE' })
    hl(0, 'NvimTreeImageFile', { fg = c.lytViolet, bg = 'NONE' })
    hl(0, 'NvimTreeEmptyFolderName', { fg = c.lytGray, bg = 'NONE' })
    hl(0, 'NvimTreeFolderName', { fg = c.lytFront, bg = 'NONE' })
    hl(0, 'NvimTreeSpecialFile', { fg = c.lytPink, bg = 'NONE', underline = true })
    hl(0, 'NvimTreeNormal', { fg = c.lytFront, bg = opts.disable_nvimtree_bg and c.lytBack or c.lytLeftDark })
    hl(0, 'NvimTreeCursorLine', { fg = 'NONE', bg = opts.disable_nvimtree_bg and c.lytCursorDarkDark or c.lytLeftMid })
    hl(0, 'NvimTreeVertSplit', { fg = opts.disable_nvimtree_bg and c.lytSplitDark or c.lytBack, bg = c.lytBack })
    hl(0, 'NvimTreeEndOfBuffer', { fg = opts.disable_nvimtree_bg and c.lytCursorDarkDark or c.lytLeftDark })
    hl(
        0,
        'NvimTreeOpenedFolderName',
        { fg = 'NONE', bg = opts.disable_nvimtree_bg and c.lytCursorDarkDark or c.lytLeftDark }
    )
    hl(0, 'NvimTreeGitRenamed', { fg = c.lytGitRenamed, bg = 'NONE' })
    hl(0, 'NvimTreeGitIgnored', { fg = c.lytGitIgnored, bg = 'NONE' })
    hl(0, 'NvimTreeGitDeleted', { fg = c.lytGitDeleted, bg = 'NONE' })
    hl(0, 'NvimTreeGitStaged', { fg = c.lytGitStageModified, bg = 'NONE' })
    hl(0, 'NvimTreeGitMerge', { fg = c.lytGitUntracked, bg = 'NONE' })
    hl(0, 'NvimTreeGitDirty', { fg = c.lytGitModified, bg = 'NONE' })
    hl(0, 'NvimTreeGitNew', { fg = c.lytGitAdded, bg = 'NONE' })

    -- Bufferline
    hl(0, 'BufferLineIndicatorSelected', { fg = c.lytLeftDark, bg = 'NONE' })
    hl(0, 'BufferLineFill', { fg = 'NONE', bg = opts.transparent and c.lytBack or c.lytLeftDark })

    -- BarBar
    hl(0, 'BufferCurrent', { fg = c.lytFront, bg = c.lytTabCurrent })
    hl(0, 'BufferCurrentIndex', { fg = c.lytFront, bg = c.lytTabCurrent })
    hl(0, 'BufferCurrentMod', { fg = c.lytYellowOrange, bg = c.lytTabCurrent })
    hl(0, 'BufferCurrentSign', { fg = c.lytFront, bg = c.lytTabCurrent })
    hl(0, 'BufferCurrentTarget', { fg = c.lytRed, bg = c.lytTabCurrent })
    hl(0, 'BufferVisible', { fg = c.lytGray, bg = c.lytTabCurrent })
    hl(0, 'BufferVisibleIndex', { fg = c.lytGray, bg = c.lytTabCurrent })
    hl(0, 'BufferVisibleMod', { fg = c.lytYellowOrange, bg = c.lytTabCurrent })
    hl(0, 'BufferVisibleSign', { fg = c.lytGray, bg = c.lytTabCurrent })
    hl(0, 'BufferVisibleTarget', { fg = c.lytRed, bg = c.lytTabCurrent })
    hl(0, 'BufferInactive', { fg = c.lytGray, bg = c.lytTabOther })
    hl(0, 'BufferInactiveIndex', { fg = c.lytGray, bg = c.lytTabOther })
    hl(0, 'BufferInactiveMod', { fg = c.lytYellowOrange, bg = c.lytTabOther })
    hl(0, 'BufferInactiveSign', { fg = c.lytGray, bg = c.lytTabOther })
    hl(0, 'BufferInactiveTarget', { fg = c.lytRed, bg = c.lytTabOther })
    hl(0, 'BufferTabpage', { fg = c.lytFront, bg = c.lytTabOther })
    hl(0, 'BufferTabpageFill', { fg = c.lytFront, bg = c.lytTabOther })
    hl(0, 'BufferTabpages', { fg = c.lytFront, bg = c.lytTabOther })
    hl(0, 'BufferTabpagesFill', { fg = c.lytFront, bg = c.lytTabOther })

    -- IndentBlankLine
    hl(0, 'IblIndent', { fg = c.lytContext, bg = 'NONE', nocombine = true })
    hl(0, 'IblWhitespace', { fg = c.lytContext, bg = 'NONE', nocombine = true })
    hl(0, 'IblScope', { fg = c.lytContextCurrent, bg = 'NONE', nocombine = true })

    -- Neotest
    hl(0, 'NeotestAdapterName', { fg = c.lytFront, bold = true })
    hl(0, 'NeotestDir', { fg = c.lytBlue })
    hl(0, 'NeotestExpandMarker', { fg = c.lytDimHighlight })
    hl(0, 'NeotestFailed', { fg = c.lytRed })
    hl(0, 'NeotestFile', { fg = c.lytBlue })
    hl(0, 'NeotestFocused', { bold = true })
    hl(0, 'NeotestIndent', { fg = c.lytDimHighlight })
    hl(0, 'NeotestMarked', { fg = c.lytYellowOrange, bold = true })
    hl(0, 'NeotestNamespace', { fg = c.lytPink })
    hl(0, 'NeotestPassed', { fg = c.lytGreen })
    hl(0, 'NeotestRunning', { fg = c.lytDarkYellow })
    hl(0, 'NeotestSkipped', { fg = c.lytBlue })
    hl(0, 'NeotestTarget', { fg = c.lytLightRed })
    hl(0, 'NeotestWatching', { fg = c.lytDarkYellow })
    hl(0, 'NeotestWinSelect', { fg = c.lytBlue, bold = true })

    -- LSP
    hl(0, 'DiagnosticOk', { fg = c.lytGreen, bg = 'NONE' })
    hl(0, 'DiagnosticError', { fg = c.lytRed, bg = 'NONE' })
    hl(0, 'DiagnosticWarn', { fg = c.lytYellow, bg = 'NONE' })
    hl(0, 'DiagnosticInfo', { fg = c.lytBlue, bg = 'NONE' })
    hl(0, 'DiagnosticHint', { fg = c.lytBlue, bg = 'NONE' })
    hl(0, 'DiagnosticUnnecessary', { fg = c.lytDisabledBlue, bg = 'NONE' })
    hl(0, 'DiagnosticUnderlineError', { fg = 'NONE', bg = 'NONE', undercurl = true, sp = c.lytRed })
    hl(0, 'DiagnosticUnderlineWarn', { fg = 'NONE', bg = 'NONE', undercurl = true, sp = c.lytYellow })
    hl(0, 'DiagnosticUnderlineInfo', { fg = 'NONE', bg = 'NONE', undercurl = true, sp = c.lytBlue })
    hl(0, 'DiagnosticUnderlineHint', { fg = 'NONE', bg = 'NONE', undercurl = true, sp = c.lytBlue })
    hl(0, 'LspReferenceText', { fg = 'NONE', bg = c.lytSelection })
    hl(0, 'LspReferenceRead', { fg = 'NONE', bg = c.lytSelection })
    hl(0, 'LspReferenceWrite', { fg = 'NONE', bg = c.lytSelection })
    hl(0, 'LspInlayHint', { fg = c.lytGray, bg = 'NONE', italic = opts.italic_inlayhints })

    -- Trouble
    hl(0, 'TroubleNormal', { link = 'Normal' })
    hl(0, 'TroubleNormalNC', { link = 'Normal' })

    -- COC.nvim
    hl(0, 'CocHighlightText', { fg = 'NONE', bg = c.lytPopupHighlightGray })
    hl(0, 'CocHighlightRead', { fg = 'NONE', bg = c.lytPopupHighlightGray })
    hl(0, 'CocHighlightWrite', { fg = 'NONE', bg = c.lytPopupHighlightGray })

    -- Nvim compe
    hl(0, 'CmpItemKindVariable', { fg = c.lytLightBlue, bg = 'NONE' })
    hl(0, 'CmpItemKindInterface', { fg = c.lytLightBlue, bg = 'NONE' })
    hl(0, 'CmpItemKindText', { fg = c.lytLightBlue, bg = 'NONE' })
    hl(0, 'CmpItemKindFunction', { fg = c.lytPink, bg = 'NONE' })
    hl(0, 'CmpItemKindMethod', { fg = c.lytPink, bg = 'NONE' })
    hl(0, 'CmpItemKindKeyword', { fg = c.lytFront, bg = 'NONE' })
    hl(0, 'CmpItemKindProperty', { fg = c.lytFront, bg = 'NONE' })
    hl(0, 'CmpItemKindUnit', { fg = c.lytFront, bg = 'NONE' })
    hl(0, 'CmpItemKindConstructor', { fg = c.lytUiOrange, bg = 'NONE' })
    hl(0, 'CmpItemMenu', { fg = c.lytPopupFront, bg = 'NONE' })
    hl(0, 'CmpItemAbbr', { fg = c.lytFront, bg = 'NONE' })
    hl(0, 'CmpItemAbbrDeprecated', { fg = c.lytCursorDark, bg = c.lytPopupBack, strikethrough = true })
    hl(0, 'CmpItemAbbrMatch', { fg = c.lytPink, bg = 'NONE', bold = true })
    hl(0, 'CmpItemAbbrMatchFuzzy', { fg = c.lytPink, bg = 'NONE', bold = true })

    -- Blink
    hl(0, 'BlinkCmpMenu', { link = 'Pmenu' })
    hl(0, 'BlinkCmpMenuBorder', { link = 'FloatBorder' })
    hl(0, 'BlinkCmpMenuSelection', { link = 'PmenuSel' })
    hl(0, 'BlinkCmpScrollBarThumb', { link = 'PmenuThumb' })
    hl(0, 'BlinkCmpScrollBarGutter', { link = 'PmenuSbar' })
    hl(0, 'BlinkCmpLabel', { fg = c.lytFront, bg = 'NONE' })
    hl(0, 'BlinkCmpLabelMatch', { fg = c.lytPink, bg = 'NONE', bold = true })
    hl(0, 'BlinkCmpLabelDetail', { fg = c.lytPopupFront, bg = 'NONE' })
    hl(0, 'BlinkCmpLabelDescription', { fg = c.lytPopupFront, bg = 'NONE' })
    hl(0, 'BlinkCmpKind', { fg = c.lytPopupFront, bg = 'NONE' })
    hl(0, 'BlinkCmpSource', { fg = c.lytPopupFront, bg = 'NONE' })
    hl(0, 'BlinkCmpGhostText', { fg = c.lytContextCurrent })
    hl(0, 'BlinkCmpDoc', { link = 'NormalFloat' })
    hl(0, 'BlinkCmpDocBorder', { link = 'FloatBorder' })
    hl(0, 'BlinkCmpDocSeparator', { link = 'NormalFloat' })
    hl(0, 'BlinkCmpDocCursorLine', { link = 'Visual' })
    hl(0, 'BlinkCmpSignatureHelp', { link = 'NormalFloat' })
    hl(0, 'BlinkCmpSignatureHelpBorder', { link = 'NormalFloat' })
    hl(0, 'BlinkCmpSignatureHelpActiveParameter', { link = 'LspSignatureActiveParameter' })

    hl(0, 'BlinkCmpKindText', { fg = c.lytPopupFront, bg = 'NONE' })
    hl(0, 'BlinkCmpKindMethod', { fg = c.lytPink, bg = 'NONE' })
    hl(0, 'BlinkCmpKindFunction', { fg = c.lytPink, bg = 'NONE' })
    hl(0, 'BlinkCmpKindConstructor', { fg = c.lytUiOrange, bg = 'NONE' })
    hl(0, 'BlinkCmpKindField', { link = '@variable.member' })
    hl(0, 'BlinkCmpKindVariable', { link = '@variable.member' })
    hl(0, 'BlinkCmpKindClass', { link = 'BlinkCmpKindConstructor' })
    hl(0, 'BlinkCmpKindInterface', { fg = c.lytLightBlue, bg = 'NONE' })
    hl(0, 'BlinkCmpKindModule', { link = 'BlinkCmpKindClass' })
    hl(0, 'BlinkCmpKindProperty', { link = 'BlinkCmpKindField' })
    hl(0, 'BlinkCmpKindUnit', { link = 'BlinkCmpKindField' })
    hl(0, 'BlinkCmpKindValue', { link = '@variable.member' })
    hl(0, 'BlinkCmpKindEnum', { link = 'BlinkCmpKindConstructor' })
    hl(0, 'BlinkCmpKindKeyword', { fg = c.lytDarkYellow, bg = 'NONE' })
    hl(0, 'BlinkCmpKindSnippet', { fg = c.lytDarkYellow, bg = 'NONE' })
    hl(0, 'BlinkCmpKindColor', { link = 'cssColor' })
    hl(0, 'BlinkCmpKindFile', { link = '@text.uri' })
    hl(0, 'BlinkCmpKindReference', { link = '@variable.parameter.reference' })
    hl(0, 'BlinkCmpKindFolder', { link = 'NeotestDir' })
    hl(0, 'BlinkCmpKindEnumMember', { link = '@variable.member' })
    hl(0, 'BlinkCmpKindConstant', { link = '@constant' })
    hl(0, 'BlinkCmpKindStruct', { link = '@structure' })
    hl(0, 'BlinkCmpKindEvent', { fg = c.lytDarkYellow, bg = 'NONE' })
    hl(0, 'BlinkCmpKindOperator', { link = '@operator' })
    hl(0, 'BlinkCmpKindTypeParameter', { link = '@variable.parameter' })
    hl(0, 'BlinkCmpKindCopilot', { fg = c.lytGreen, bg = 'NONE' })

    -- HiPhish/rainbow-delimiters.nvim
    hl(0, 'RainbowDelimiterRed', { fg = c.lytPink, bg = 'NONE' })
    hl(0, 'RainbowDelimiterOrange', { fg = c.lytOrange, bg = 'NONE' })
    hl(0, 'RainbowDelimiterYellow', { fg = c.lytYellow, bg = 'NONE' })
    hl(0, 'RainbowDelimiterGreen', { fg = c.lytGreen, bg = 'NONE' })
    hl(0, 'RainbowDelimiterCyan', { fg = c.lytGreen, bg = 'NONE' })
    hl(0, 'RainbowDelimiterBlue', { fg = c.lytAccentBlue, bg = 'NONE' })
    hl(0, 'RainbowDelimiterViolet', { fg = c.lytViolet, bg = 'NONE' })

    -- rcarriga/nvim-dap-ui
    -- Source: https://github.com/rcarriga/nvim-dap-ui/blob/master/lua/dapui/config/highlights.lua
    hl(0, 'DapUIBreakpointsCurrentLine', { fg = c.lytGreen, bold = true })
    hl(0, 'DapUIBreakpointsDisabledLine', { fg = c.lytDimHighlight })
    hl(0, 'DapUIBreakpointsInfo', { fg = c.lytGreen })
    hl(0, 'DapUIBreakpointsLine', { fg = c.lytPink })
    hl(0, 'DapUIBreakpointsPath', { fg = c.lytPink })
    hl(0, 'DapUICurrentFrameName', { fg = c.lytGreen, bold = true })
    hl(0, 'DapUIDecoration', { fg = c.lytPink })
    hl(0, 'DapUIFloatBorder', { fg = c.lytPink })
    hl(0, 'DapUILineNumber', { fg = c.lytPink })
    hl(0, 'DapUIModifiedValue', { fg = c.lytPink, bold = true })
    hl(0, 'DapUIPlayPause', { fg = c.lytGreen })
    hl(0, 'DapUIPlayPauseNC', { fg = c.lytGreen })
    hl(0, 'DapUIRestart', { fg = c.lytGreen })
    hl(0, 'DapUIRestartNC', { fg = c.lytGreen })
    hl(0, 'DapUIScope', { fg = c.lytPink })
    hl(0, 'DapUISource', { fg = c.lytAccentBlue })
    hl(0, 'DapUIStepBack', { fg = c.lytPink })
    hl(0, 'DapUIStepBackNC', { fg = c.lytPink })
    hl(0, 'DapUIStepInto', { fg = c.lytPink })
    hl(0, 'DapUIStepIntoNC', { fg = c.lytPink })
    hl(0, 'DapUIStepOut', { fg = c.lytPink })
    hl(0, 'DapUIStepOutNC', { fg = c.lytPink })
    hl(0, 'DapUIStepOver', { fg = c.lytPink })
    hl(0, 'DapUIStepOverNC', { fg = c.lytPink })
    hl(0, 'DapUIStop', { fg = c.lytRed })
    hl(0, 'DapUIStopNC', { fg = c.lytRed })
    hl(0, 'DapUIStoppedThread', { fg = c.lytPink })
    hl(0, 'DapUIThread', { fg = c.lytGreen })
    hl(0, 'DapUIType', { fg = c.lytPink })
    hl(0, 'DapUIUnavailable', { fg = c.lytDimHighlight })
    hl(0, 'DapUIUnavailableNC', { fg = c.lytDimHighlight })
    hl(0, 'DapUIWatchesEmpty', { fg = c.lytDimHighlight })
    hl(0, 'DapUIWatchesError', { fg = c.lytRed })
    hl(0, 'DapUIWatchesValue', { fg = c.lytGreen })
    hl(0, 'DapUIWinSelect', { fg = c.lytPink, bold = true })

    -- Dashboard
    hl(0, 'DashboardHeader', { fg = c.lytBlue, bg = 'NONE' })
    hl(0, 'DashboardDesc', { fg = c.lytYellowOrange, bg = 'NONE' })
    hl(0, 'DashboardIcon', { fg = c.lytYellowOrange, bg = 'NONE' })
    hl(0, 'DashboardShortCut', { fg = c.lytPink, bg = 'NONE' })
    hl(0, 'DashboardKey', { fg = c.lytWhite, bg = 'NONE' })
    hl(0, 'DashboardFooter', { fg = c.lytBlue, bg = 'NONE', italic = true })

    -- Illuminate
    hl(0, 'illuminatedWord', { bg = c.lytPopupHighlightGray })
    hl(0, 'illuminatedCurWord', { bg = c.lytPopupHighlightGray })
    hl(0, 'IlluminatedWordText', { bg = c.lytPopupHighlightGray })
    hl(0, 'IlluminatedWordRead', { bg = c.lytPopupHighlightGray })
    hl(0, 'IlluminatedWordWrite', { bg = c.lytPopupHighlightGray })

    -- mini.statusline
    hl(0, 'MiniStatuslineModeNormal', { bg = c.lytLeftDark, fg = c.lytFront })
    hl(0, 'MiniStatuslineModeInsert', { bg = c.lytLeftDark, fg = c.lytFront })
    hl(0, 'MiniStatuslineModeVisual', { bg = c.lytLeftDark, fg = c.lytFront })
    hl(0, 'MiniStatuslineModeReplace', { bg = c.lytLeftDark, fg = c.lytFront })
    hl(0, 'MiniStatuslineModeCommand', { bg = c.lytLeftDark, fg = c.lytFront })
    hl(0, 'MiniStatuslineModeOther', { bg = c.lytLeftDark, fg = c.lytFront })
    hl(0, 'MiniStatuslineDevinfo', { bg = c.lytLeftDark, fg = c.lytFront })
    hl(0, 'MiniStatuslineFilename', { bg = c.lytLeftMid, fg = c.lytFront })
    hl(0, 'MiniStatuslineFileinfo', { bg = c.lytLeftLight, fg = c.lytFront })
    hl(0, 'MiniStatuslineInactive', { bg = c.lytLeftDark, fg = c.lytFront })

    -- mini.icons
    hl(0, 'MiniIconsAzure', { fg = c.lytBlue })
    hl(0, 'MiniIconsBlue', { fg = c.lytAccentBlue })
    hl(0, 'MiniIconsCyan', { fg = c.lytGreen })
    hl(0, 'MiniIconsGreen', { fg = c.lytGreen })
    hl(0, 'MiniIconsGrey', { fg = c.lytFront })
    hl(0, 'MiniIconsOrange', { fg = c.lytRed })
    hl(0, 'MiniIconsPurple', { fg = c.lytPink })
    hl(0, 'MiniIconsRed', { fg = c.lytRed })
    hl(0, 'MiniIconsYellow', { fg = c.lytDarkYellow })

    -- Neotree
    hl(0, 'NeoTreeBufferNumber', { fg = c.lytLineNumber, bg = 'NONE' })
    hl(0, 'NeoTreeCursorLine', { fg = 'NONE', bg = c.lytCursorDarkDark })
    hl(0, 'NeoTreeDimText', { fg = 'NONE', bg = c.lytCursorDarkDark })
    hl(0, 'NeoTreeDirectoryIcon', { fg = c.lytBlue, bg = 'NONE' })
    hl(0, 'NeoTreeDirectoryName', { fg = c.lytFront, bg = 'NONE' })
    hl(0, 'NeoTreeDotfile', { fg = c.lytDisabledBlue, bg = 'NONE' })
    hl(0, 'NeoTreeFileIcon', { fg = c.lytViolet, bg = 'NONE' })
    hl(0, 'NeoTreeFileName', { fg = c.lytFront, bg = 'NONE' })
    hl(0, 'NeoTreeFileNameOpened', { fg = c.lytFront, bg = c.lytCursorDarkDark })
    hl(0, 'NeoTreeFilterTerm', { fg = c.lytFront, bg = 'NONE' })
    hl(0, 'NeoTreeFloatBorder', { fg = c.lytLineNumber, bg = 'NONE' })
    hl(0, 'NeoTreeFloatTitle', { fg = c.lytLineNumber, bg = 'NONE' })
    hl(0, 'NeoTreeTitleBar', { fg = c.lytLineNumber, bg = 'NONE' })

    -- Snacks nvim
    hl(0, 'SnacksPicker', { link = 'Normal' })
    hl(0, 'SnacksPickerBorder', { link = 'Normal' })
    hl(0, 'SnacksPickerDir', { fg = 'NONE', bg = 'NONE', nocombine = true })
    hl(0, 'SnacksPickerDirectory', { fg = 'NONE', bg = 'NONE', nocombine = true })
    hl(0, 'SnacksIndent', { fg = c.lytContext, bg = 'NONE', nocombine = true })
    hl(0, 'SnacksPickerListCursorLine', { link = 'PmenuSel' })
    hl(0, 'SnacksPickerPreviewCursorLine', { fg = 'none', bg = 'none', nocombine = true })

    -- Compiler mode nvim
    hl(0, 'CompileModeMessage', { underline = true })
    hl(0, 'CompileModeMessageRow', { fg = c.lytPink })
    hl(0, 'CompileModeMessageCol', { fg = c.lytGreen })
    hl(0, 'CompileModeError', { fg = c.lytRed })
    hl(0, 'CompileModeWarning', { fg = c.lytYellow })
    hl(0, 'CompileModeInfo', { fg = c.lytGreen })
    hl(0, 'CompileModeCommandOutput', { fg = '#6699ff' })
    hl(0, 'CompileModeDirectoryMessage', { fg = '#6699ff' })
    hl(0, 'CompileModeOutputFile', { fg = '#9966cc' })
    hl(0, 'CompileModeCheckResult', { fg = '#ff9966', bold = true })
    hl(0, 'CompileModeCheckTarget', { fg = '#ff9966' })
    hl(0, 'CompileModeErrorLocus', { link = 'Visual' })

    -- Mini Statusline
    hl(0, 'MiniStatuslineDevinfo', { bg = c.lytLeftLight })
    hl(0, 'MiniStatuslineFileinfo', { bg = c.lytLeftLight })
    hl(0, 'MiniStatuslineModeCommand', { fg = c.lytBack, bg = c.lytLightRed, bold = true })
    hl(0, 'MiniStatuslineModeInsert', { fg = c.lytBack, bg = c.lytLightBlue, bold = true })
    hl(0, 'MiniStatuslineModeNormal', { fg = c.lytBack, bg = c.lytYellow, bold = true })
    hl(0, 'MiniStatuslineModeReplace', { fg = c.lytBack, bg = c.lytYellowOrange, bold = true })
    hl(0, 'MiniStatuslineModeVisual', { fg = c.lytBack, bg = c.lytPink, bold = true })

    -- Copilot
    hl(0, 'CopilotSuggestion', { fg = c.lytSuggestion, bg = 'NONE' })

    -- NeogitOrg/neogit
    hl(0, 'NeogitWinSeparator', { link = 'WinSeparator' })
    hl(0, 'NeogitDiffAdd', { fg = c.lytGitAdded, bg = c.lytDiffGreenDark })
    hl(0, 'NeogitDiffAddHighlight', { fg = c.lytGitAdded, bg = c.lytDiffGreenLight })
    hl(0, 'NeogitDiffContext', { fg = c.lytPopupFront, bg = c.lytLeftDark })
    hl(0, 'NeogitDiffContextHighlight', { fg = c.lytPopupFront, bg = c.lytLeftMid })
    hl(0, 'NeogitDiffDelete', { fg = c.lytGitDeleted, bg = c.lytDiffRedDark })
    hl(0, 'NeogitDiffDeleteHighlight', { fg = c.lytGitDeleted, bg = c.lytDiffRedLight })
    hl(0, 'NeogitDiffHeader', { fg = c.lytSplitLight, bg = c.lytBack })
    hl(0, 'NeogitDiffHeaderHighlight', { fg = c.lytSplitLight, bg = c.lytBack })
    hl(0, 'NeogitHunkHeader', { fg = c.lytGitModified, bg = c.lytLeftDark })
    hl(0, 'NeogitHunkHeaderHighlight', { fg = c.lytGitModified, bg = c.lytLeftMid })

    -- Cursor line highlights cause way too much distraction; rely on the
    -- pointer and regular highlight colors:
    hl(0, 'NeogitDiffAddCursor', { link = 'NeogitDiffAddHighlight' })
    hl(0, 'NeogitDiffContextCursor', { link = 'NeogitDiffContextHighlight' })
    hl(0, 'NeogitDiffDeleteCursor', { link = 'NeogitDiffDeleteHighlight' })
    hl(0, 'NeogitHunkHeaderCursor', { link = 'NeogitHunkHeaderHighlight' })

    hl(0, 'NvimTreeFolderIcon', { fg = c.lytBlue, bg = 'NONE' })
    hl(0, 'NvimTreeIndentMarker', { fg = c.lytLineNumber, bg = 'NONE' })

    hl(0, 'LspFloatWinNormal', { fg = c.lytFront, bg = 'NONE' })
    hl(0, 'LspFloatWinBorder', { fg = c.lytLineNumber, bg = 'NONE' })
    hl(0, 'LspInfoBorder', { fg = c.lytLineNumber, bg = 'NONE' })
    hl(0, 'LspSagaHoverBorder', { fg = c.lytLineNumber, bg = 'NONE' })
    hl(0, 'LspSagaSignatureHelpBorder', { fg = c.lytLineNumber, bg = 'NONE' })
    hl(0, 'LspSagaCodeActionBorder', { fg = c.lytLineNumber, bg = 'NONE' })
    hl(0, 'LspSagaDefPreviewBorder', { fg = c.lytLineNumber, bg = 'NONE' })
    hl(0, 'LspLinesDiagBorder', { fg = c.lytLineNumber, bg = 'NONE' })
    hl(0, 'LspSagaRenameBorder', { fg = c.lytLineNumber, bg = 'NONE' })
    hl(0, 'LspSagaBorderTitle', { fg = c.lytCursorDark, bg = 'NONE' })
    hl(0, 'LSPSagaDiagnosticTruncateLine', { fg = c.lytLineNumber, bg = 'NONE' })
    hl(0, 'LspSagaDiagnosticBorder', { fg = c.lytLineNumber, bg = 'NONE' })
    hl(0, 'LspSagaDiagnosticBorder', { fg = c.lytLineNumber, bg = 'NONE' })
    hl(0, 'LspSagaShTruncateLine', { fg = c.lytLineNumber, bg = 'NONE' })
    hl(0, 'LspSagaShTruncateLine', { fg = c.lytLineNumber, bg = 'NONE' })
    hl(0, 'LspSagaDocTruncateLine', { fg = c.lytLineNumber, bg = 'NONE' })
    hl(0, 'LspSagaRenameBorder', { fg = c.lytLineNumber, bg = 'NONE' })
    hl(0, 'LspSagaLspFinderBorder', { fg = c.lytLineNumber, bg = 'NONE' })

    hl(0, 'TelescopePromptBorder', { fg = c.lytLineNumber, bg = 'NONE' })
    hl(0, 'TelescopeResultsBorder', { fg = c.lytLineNumber, bg = 'NONE' })
    hl(0, 'TelescopePreviewBorder', { fg = c.lytLineNumber, bg = 'NONE' })
    hl(0, 'TelescopeNormal', { fg = c.lytFront, bg = 'NONE' })
    hl(0, 'TelescopeSelection', { fg = c.lytFront, bg = c.lytPopupHighlightBlue })
    hl(0, 'TelescopeMultiSelection', { fg = c.lytFront, bg = c.lytPopupHighlightBlue })
    hl(0, 'TelescopeMatching', { fg = c.lytPink, bg = 'NONE', bold = true })
    hl(0, 'TelescopePromptPrefix', { fg = c.lytFront, bg = 'NONE' })

    -- Debugging
    hl(0, 'debugPC', { bg = '#4C4C19' })

    -- symbols-outline
    -- white fg and lualine blue bg
    hl(0, 'FocusedSymbol', { fg = '#ffffff', bg = c.lytUiBlue })
    hl(0, 'SymbolsOutlineConnector', { fg = c.lytLineNumber, bg = 'NONE' })
end

theme.link_highlight = function()
    -- Legacy groups for official git.vim and diff.vim syntax
    hl(0, 'diffAdded', { link = 'DiffAdd' })
    hl(0, 'diffChanged', { link = 'DiffChange' })
    hl(0, 'diffRemoved', { link = 'DiffDelete' })
    -- Legacy groups for treesitter
    hl(0, '@parameter', { link = '@variable.parameter' })
    hl(0, '@field', { link = '@variable.member' })
    hl(0, '@string.regex', { link = '@string.regexp' })
    hl(0, '@float', { link = '@number.float' })
    hl(0, '@namespace', { link = '@module' })
    hl(0, '@method', { link = '@function.method' })
    hl(0, '@field', { link = '@variable.member' })
    hl(0, '@conditional', { link = '@keyword.conditional' })
    hl(0, '@repeat', { link = '@keyword.repeat' })
    hl(0, '@exception', { link = '@keyword.exception' })
    hl(0, '@storageclass', { link = '@keyword.storage' })
    hl(0, '@include', { link = '@keyword.import' })
    hl(0, '@text.strong', { link = '@markup.strong' })
    hl(0, '@text.underline', { link = '@markup.underline' })
    hl(0, '@text.emphasis', { link = '@markup.italic' })
    hl(0, '@text.strike', { link = '@markup.strikethrough' })
    hl(0, '@text.title', { link = '@markup.heading' })
    hl(0, '@text.uri', { link = '@markup.link.url' })
    hl(0, '@text.literal', { link = '@markup.raw' })
    hl(0, '@text.note', { link = '@comment.note' })
    hl(0, '@text.warning', { link = '@comment.warning' })
    hl(0, '@text.danger', { link = '@comment.error' })
    hl(0, '@text.diff.add', { link = '@diff.plus' })
    hl(0, '@text.diff.delete', { link = '@diff.minus' })
    -- Nvim compe
    hl(0, 'CompeDocumentation', { link = 'Pmenu' })
    hl(0, 'CompeDocumentationBorder', { link = 'Pmenu' })
    hl(0, 'CmpItemKind', { link = 'Pmenu' })
    hl(0, 'CmpItemKindClass', { link = 'CmpItemKindConstructor' })
    hl(0, 'CmpItemKindModule', { link = 'CmpItemKindKeyword' })
    hl(0, 'CmpItemKindOperator', { link = '@operator' })
    hl(0, 'CmpItemKindReference', { link = '@variable.parameter.reference' })
    hl(0, 'CmpItemKindValue', { link = '@variable.member' })
    hl(0, 'CmpItemKindField', { link = '@variable.member' })
    hl(0, 'CmpItemKindEnum', { link = '@variable.member' })
    hl(0, 'CmpItemKindSnippet', { link = '@text' })
    hl(0, 'CmpItemKindColor', { link = 'cssColor' })
    hl(0, 'CmpItemKindFile', { link = '@text.uri' })
    hl(0, 'CmpItemKindFolder', { link = '@text.uri' })
    hl(0, 'CmpItemKindEvent', { link = '@constant' })
    hl(0, 'CmpItemKindEnumMember', { link = '@variable.member' })
    hl(0, 'CmpItemKindConstant', { link = '@constant' })
    hl(0, 'CmpItemKindStruct', { link = '@structure' })
    hl(0, 'CmpItemKindTypeParameter', { link = '@variable.parameter' })
end

return theme
